[2024-07-13T10:50:30.660+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T10:50:30.702+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: deploy_flask_app.build_image scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2024-07-13T10:50:30.716+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: deploy_flask_app.build_image scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2024-07-13T10:50:30.717+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-13T10:50:30.741+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): build_image> on 2023-04-10 00:00:00+00:00
[2024-07-13T10:50:30.757+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=316) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-13T10:50:30.762+0000] {standard_task_runner.py:63} INFO - Started process 332 to run task
[2024-07-13T10:50:30.764+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'deploy_flask_app', 'build_image', 'scheduled__2023-04-10T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/deploy_flask_app.py', '--cfg-path', '/tmp/tmpw2st1mrx']
[2024-07-13T10:50:30.769+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask build_image
[2024-07-13T10:50:30.898+0000] {task_command.py:426} INFO - Running <TaskInstance: deploy_flask_app.build_image scheduled__2023-04-10T00:00:00+00:00 [running]> on host e9ee640206e7
[2024-07-13T10:50:31.172+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='deploy_flask_app' AIRFLOW_CTX_TASK_ID='build_image' AIRFLOW_CTX_EXECUTION_DATE='2023-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-10T00:00:00+00:00'
[2024-07-13T10:50:31.186+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T10:50:31.203+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-13T10:50:31.214+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker build -t my-flask-app .']
[2024-07-13T10:50:31.242+0000] {subprocess.py:86} INFO - Output:
[2024-07-13T10:50:31.456+0000] {subprocess.py:93} INFO - DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
[2024-07-13T10:50:31.462+0000] {subprocess.py:93} INFO -             Install the buildx component to build images with BuildKit:
[2024-07-13T10:50:31.462+0000] {subprocess.py:93} INFO -             https://docs.docker.com/go/buildx/
[2024-07-13T10:50:31.462+0000] {subprocess.py:93} INFO - 
[2024-07-13T10:50:31.463+0000] {subprocess.py:93} INFO - unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/***tmpstl0awvo/Dockerfile: no such file or directory
[2024-07-13T10:50:31.463+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-13T10:50:31.467+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T10:50:31.502+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-13T10:50:31.519+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=deploy_flask_app, task_id=build_image, run_id=scheduled__2023-04-10T00:00:00+00:00, execution_date=20230410T000000, start_date=20240713T105030, end_date=20240713T105031
[2024-07-13T10:50:31.543+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 77 for task build_image (Bash command failed. The command returned a non-zero exit code 1.; 332)
[2024-07-13T10:50:31.598+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-13T10:50:31.610+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
